### PR TITLE
Facelift website

### PR DESCRIPTION
**Pull request by TobyAsE**
I moved some stuff around and got rid of the carousel, instead the features are displayed in cards.
I was careful about responsibility, it should look nice on every device.

This is how it looks now on my branch ((imagine the footer at the bottom, artifact of screenshot)):
image

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Attempt to provide a better picture (:
изображение
изображение
изображение

**Comment by MrNaif2018** [comment]
@TobyAsE Can this PR marked as not draft now? Is there something unfinished?

**Comment by TobyAsE** [comment]
I think it can be merged now.
If there are any problems we'll find and fix them...

**Comment by MrNaif2018** [comment]
Thank you very much for your great work! Merged!

**Pull request merged**
